### ISSUE TITLE
白皮书第22页表3.2.1 FMC协议流程

### ISSUE THREAD

**Issue by lidh15** [tongdun/ibond_flex#1]
此处的“根据接收到的随机矩阵生成碎- 片”的具体实现是什么？
根据表中具体步骤，有
```
X1碎片T X2 + U1 + U2 - R1T X2碎片 = X1T X2
```
如何得到上述结果？R2在计算中未出现，其作用是什么？

**Comment by yuzhangTD** [comment]
在协调方初始化的时候，有R1T R2 = U1+U2，基于矩阵计算可以得到上式。
